name: 'Platformatic DB Deployer'
description: 'Deploy a Platformatic DB application to the cloud'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  platformatic_api_key:
    description: 'Platformatic API key'
    required: true
  platformatic_config_path:
    description: 'Path to the Platformatic config file'
    required: false
  platformatic_env_path:
    description: 'Path to the Platformatic config file'
    required: false
  steve_server_url:
    description: 'Url to the Steve server (test parameter)'
    required: true
  harry_server_url:
    description: 'Url to the Harry server (test parameter)'
    required: true
outputs:
  platformatic_app_url:
    description: 'URL of the deployed Platformatic DB application'
runs:
  using: 'node16'
  main: 'index.js'
