name: 'Platformatic DB Deployer'
description: 'Deploy a Platformatic DB application to the cloud'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  platformatic_workspace_id:
    description: 'Platformatic workspace ID'
    required: true
  platformatic_workspace_key:
    description: 'Platformatic workspace key'
    required: true
  platformatic_config_path:
    description: 'Path to the Platformatic config file'
    required: false
  platformatic_env_path:
    description: 'Path to the Platformatic config file'
    required: false
  allowed_env_vars:
    description: 'Comma separated list of environment variables to be passed to the Platformatic DB application'
    required: false
  steve_server_url:
    description: 'URL of the Steve server'
    required: false
  harry_server_url:
    description: 'URL of the Harry server'
    required: false
outputs:
  platformatic_app_url:
    description: 'URL of the deployed Platformatic DB application'
runs:
  using: 'node16'
  main: 'index.js'
